# Generated by Django 3.2.18 on 2023-07-27 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='order',
            name='product_code',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
